export const CUSTOMERS = [
  {
    "id": 1,
    "name": "Kelsie Roy",
    "email": "roykelsie@gmail.com",
    "phone": "",
    "location": "120 Gallup Hill Rd Apt 3A, Ledyard, Connecticut, 06339-1617, United States, 06339-1617",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 60.0,
    "totalAmount": 60.0,
    "instagram": ""
  },
  {
    "id": 2,
    "name": "Robyn Fitzgerald",
    "email": "robynfitzgerald34@gamail.com",
    "phone": "",
    "location": "10 Mill Cl, The Crescent, Kilcock, MH, W23 AHP9, Ireland, W23 AHP9",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": ""
  },
  {
    "id": 3,
    "name": "Sharon BROUGH",
    "email": "shrn1972@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": ""
  },
  {
    "id": 4,
    "name": "Maxwell Dacosta",
    "email": "maxwelldondacosta@gmail.com",
    "phone": "",
    "location": "60 Lincoln Rd, Enfield, ENG, EN1 1JS, United Kingdom, EN1 1JS",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 66.0,
    "totalAmount": 66.0,
    "instagram": ""
  },
  {
    "id": 5,
    "name": "Kelly Jean",
    "email": "kj.model.mt@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": ""
  },
  {
    "id": 6,
    "name": "Jennifer Outen",
    "email": "jennifer.outen@gmail.com",
    "phone": "",
    "location": "1055 Valley Forge Rd, Clover, South Carolina, 29710-6060, United States, 29710-6060",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 70.0,
    "totalAmount": 112.0,
    "instagram": ""
  },
  {
    "id": 7,
    "name": "Amy Belleville",
    "email": "amylouisebelleville@gmail.com",
    "phone": "",
    "location": "107/1101 Toorak Rd, Camberwell, VIC, 3124, Australia, 3124",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 70.0,
    "totalAmount": 70.0,
    "instagram": ""
  },
  {
    "id": 8,
    "name": "Tyrrilly Phillips",
    "email": "atlasphillips@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": ""
  },
  {
    "id": 9,
    "name": "Mohammod Ashiq ur Rahman",
    "email": "ash.mr2016@gmail.com",
    "phone": "",
    "location": "106 Healy Ave, Gregory Hills, NSW, 2557, Australia, 2557",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": ""
  },
  {
    "id": 10,
    "name": "Ally Arnott",
    "email": "allykat12321@gmail.com",
    "phone": "",
    "location": "915 knapp street, OSHKOSH, Wisconsin, 54901, United States, 54901",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": ""
  },
  {
    "id": 11,
    "name": "Heather Kaminski",
    "email": "erica.jane.modeling@gmail.com",
    "phone": "",
    "location": "16 ten lots road, Oakland, Maine, 04937, United States, 4937",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": ""
  },
  {
    "id": 12,
    "name": "Fiona Shaw",
    "email": "saucyaussiegirl@gmail.com",
    "phone": "",
    "location": "1339 Timber Glen Drive, Wilmington, Ohio, 45177, United States, 45177",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": ""
  },
  {
    "id": 13,
    "name": "Anyana Webb-Stains",
    "email": "anyanawebbphotography@gmail.com",
    "phone": "",
    "location": "17289 Three Oaks Lane, Lathrop, California, 95330, United States, 95330",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 50.0,
    "totalAmount": 50.0,
    "instagram": ""
  },
  {
    "id": 14,
    "name": "Gloria Fernandez",
    "email": "gloriafernandezp84@hotmail.com",
    "phone": "",
    "location": "",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": ""
  },
  {
    "id": 15,
    "name": "Soraya Lamkadmi",
    "email": "sorayalamkadmi@icloud.com",
    "phone": "",
    "location": "",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 23.99,
    "totalAmount": 23.99,
    "instagram": ""
  },
  {
    "id": 16,
    "name": "Yvonne Kasamani",
    "email": "malaikaevie@gmail.com",
    "phone": "",
    "location": "3875 Oak View Court, Turlock, California, 95382, United States, 95382",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 82.0,
    "totalAmount": 82.0,
    "instagram": ""
  },
  {
    "id": 17,
    "name": "Patricia Martin",
    "email": "pattim68@telus.net",
    "phone": "",
    "location": "5805 182, Surrey, British Columbia, V3S 4T4, Canada, V3S 4T4",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 70.0,
    "totalAmount": 70.0,
    "instagram": ""
  },
  {
    "id": 18,
    "name": "Juan Soto Naranjo",
    "email": "JSebastian_Soto@live.com",
    "phone": "",
    "location": "",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": ""
  },
  {
    "id": 19,
    "name": "rick crauwels",
    "email": "rick@crauwels.nl",
    "phone": "",
    "location": "",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 22.49,
    "totalAmount": 22.49,
    "instagram": ""
  },
  {
    "id": 20,
    "name": "Belinda Lam",
    "email": "info@bellephotojourney.com",
    "phone": "",
    "location": "c/o Nikhil Ochani, Apt 109, 10 Park Drive,, London, ENG, E14 9ZW, United Kingdom, E14 9ZW",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": ""
  },
  {
    "id": 21,
    "name": "IORDANA TSIKOU",
    "email": "taniakokkinou402@gmail.com",
    "phone": "",
    "location": "Offenbach am Main, HE, Germany, Fritz-Remy-Stra\u00dfe, 63071",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": ""
  },
  {
    "id": 22,
    "name": "Dahmein mcfadden",
    "email": "dahmein@verizon.net",
    "phone": "",
    "location": "3 Richard C Brown Dr, Stony Point, New York, 10980-3008, United States, 10980-3008",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": ""
  },
  {
    "id": 23,
    "name": "Zoya Zimmerman",
    "email": "zoyazimmerman@ymail.com",
    "phone": "",
    "location": "10068 E Arizona Drive, 1831, Denver, Colorado, 80247, United States, 80247",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 79.98,
    "totalAmount": 79.98,
    "instagram": ""
  },
  {
    "id": 24,
    "name": "Jasmin Grundig",
    "email": "minegrundig@googlemail.com",
    "phone": "",
    "location": "Lindenweg 1, Oschersleben (Bode), 39387, Germany, 39387",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": ""
  },
  {
    "id": 25,
    "name": "NICOLAS FOSSA",
    "email": "dir.finance@imer.fr",
    "phone": "",
    "location": "",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 59.98,
    "instagram": ""
  },
  {
    "id": 26,
    "name": "JULIET SAN VICENTE",
    "email": "duckdaisy59@gmail.com",
    "phone": "",
    "location": "Flat 34 Beauclere House 67 Brighton Road, Sutton, ENG, SM2 5BT, United Kingdom, SM2 5BT",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": ""
  },
  {
    "id": 27,
    "name": "Andrea Ceccaroni",
    "email": "andrea.ceccaroni87@gmail.com",
    "phone": "",
    "location": "Via Cesare Balbo 19, Torino, 21, 10124, Italy, 10124",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": ""
  },
  {
    "id": 28,
    "name": "Rebekka Kruft",
    "email": "RebekkaBrunner@web.de",
    "phone": "",
    "location": "M\u00f6nchstieg 1, Wernigerode, 38855, Germany, 38855",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": ""
  },
  {
    "id": 29,
    "name": "Trevor Stiles",
    "email": "raconteurimagery@gmail.com",
    "phone": "",
    "location": "870 Saint Andrews Drive, Oconomowoc, Wisconsin, 53066, United States, 53066",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": ""
  },
  {
    "id": 30,
    "name": "Victoria Carcenac",
    "email": "carcenacvictoria@gmail.com",
    "phone": "",
    "location": "139 Chemin de la Guiraudi\u00e9, Roumegoux, OCC, 81120, France, 81120",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": ""
  },
  {
    "id": 31,
    "name": "Ulrike Swoboda-peters",
    "email": "ulliswobi@hotmail.de",
    "phone": "",
    "location": "In der Lusenheide 9, Oer-Erkenschwick, 45739, Germany, 45739",
    "magazine": "ALPHERO",
    "status": "Buyer",
    "amount": 89.98,
    "totalAmount": 89.98,
    "instagram": ""
  },
  {
    "id": 32,
    "name": "Lorenzo Torres",
    "email": "dappershoots@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 23.99,
    "totalAmount": 23.99,
    "instagram": "Http://www.instagram.com/black.Majenta"
  },
  {
    "id": 33,
    "name": "nan DuBose",
    "email": "demarcus.dubose@gmail.com",
    "phone": "",
    "location": "1431 Rowan Oak, Tupelo, Mississippi, 38801, United States, 38801",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "https://www.instagram.com/yuri_the_photographer//"
  },
  {
    "id": 34,
    "name": "Remi-Morgan Graham",
    "email": "remorgangra@gmail.com",
    "phone": "",
    "location": "27 Earlsmead Rd, Birmingham, ENG, B21 0HU, United Kingdom, B21 0HU",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "https://www.instagram.com/lenworth.johnson/"
  },
  {
    "id": 35,
    "name": "Joi Crawford",
    "email": "joic17@gmail.com",
    "phone": "",
    "location": "5474 Oakley Industrial Blvd apt 735, Fairburn, Georgia, 30213, United States, 30213",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 70.0,
    "totalAmount": 70.0,
    "instagram": "https://instagram.com/mephotography214?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 36,
    "name": "Amber Shumway",
    "email": "ashumway204@gmail.com",
    "phone": "",
    "location": "25729 E Polk Pl, Aurora, Colorado, 80016-7302, United States, 80016-7302",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 160.0,
    "totalAmount": 160.0,
    "instagram": "Www.Instagram.com/beniciaciara/"
  },
  {
    "id": 37,
    "name": "Chriselly West",
    "email": "chrisellyw1@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 23.99,
    "totalAmount": 23.99,
    "instagram": "https://www.instagram.com/modeljaja/"
  },
  {
    "id": 38,
    "name": "Dez Durden",
    "email": "dezmd20@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 23.99,
    "totalAmount": 23.99,
    "instagram": "https://instagram.com/_dstyles_?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 39,
    "name": "Leola Meristil",
    "email": "lele2545@gmail.com",
    "phone": "",
    "location": "8523 Williams Ave, Philadelphia, Pennsylvania, 19150, United States, 19150",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://www.instagram.com/prevalentfocus/"
  },
  {
    "id": 40,
    "name": "Mya Smith",
    "email": "myasmiithh@gmail.com",
    "phone": "",
    "location": "2244 steeplechase road, Canton, Michigan, 48188, United States, 48188",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 70.0,
    "totalAmount": 70.0,
    "instagram": "https://www.instagram.com/royal_paradisexo/?hl=en"
  },
  {
    "id": 41,
    "name": "Milton Hudson",
    "email": "milt_52001@yahoo.com",
    "phone": "",
    "location": "169 Lomita Heights Dr, Las Vegas, Nevada, 89138, United States, 89138",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://www.instagram.com/annekapresston/"
  },
  {
    "id": 42,
    "name": "Fadylah Ameer",
    "email": "fadylahmodels@gmail.com",
    "phone": "",
    "location": "8315 Delmar Blvd, St. Louis, Missouri, 63124-2145, United States, 63124-2145",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 70.0,
    "totalAmount": 70.0,
    "instagram": "https://www.instagram.com/annekapresston/"
  },
  {
    "id": 43,
    "name": "Enicka Neal",
    "email": "enickaneal@yahoo.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": "https://www.instagram.com/annekapresston/"
  },
  {
    "id": 44,
    "name": "Jay Sweeney",
    "email": "jay.sweeney3@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": "https://www.instagram.com/miss.Parker/"
  },
  {
    "id": 45,
    "name": "Kimberly Mills",
    "email": "kimberlyjoyphotos@gmail.com",
    "phone": "",
    "location": "3704 Oak Leaf Way #C, Greenville, North Carolina, 27834-4409, United States, 27834-4409",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "https://www.instagram.com/chloepistle/"
  },
  {
    "id": 46,
    "name": "Tonya Robinson",
    "email": "tsealsrobinson@gmail.com",
    "phone": "",
    "location": "6630 Crest Ave, University City, Missouri, 63130-2604, United States, 63130-2604",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 66.0,
    "totalAmount": 66.0,
    "instagram": "https://www.instagram.com/seanasparkle/"
  },
  {
    "id": 47,
    "name": "Eldric Charlot",
    "email": "eldriccharlotvision@gmail.com",
    "phone": "",
    "location": "137 Parro Ln, Berwick, Louisiana, 70342-2081, United States, 70342-2081",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 50.0,
    "totalAmount": 50.0,
    "instagram": "https://www.instagram.com/reighanna_brown/"
  },
  {
    "id": 48,
    "name": "Joyce Cleary",
    "email": "msjchuck25@gmail.com",
    "phone": "",
    "location": "4411 Springdale Ave., Baltimore, Maryland, 21207, United States, 21207",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://www.instagram.com/_blessinlashay/"
  },
  {
    "id": 49,
    "name": "Carlos A Velarde",
    "email": "alluringexposures@gmail.com",
    "phone": "",
    "location": "851 W Moon Shadow Dr, Casa Grande, Arizona, 85122-7890, United States, 85122-7890",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 66.0,
    "totalAmount": 66.0,
    "instagram": "https://www.instagram.com/Youngartistinthemist/"
  },
  {
    "id": 50,
    "name": "Kryzma Young",
    "email": "kryzma.young32@gmail.com",
    "phone": "",
    "location": "2722 Kinloch Dr, Orlando, Florida, 32817-2629, United States, 32817-2629",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 70.0,
    "totalAmount": 70.0,
    "instagram": "https://www.instagram.com/Youngartistinthemist/"
  },
  {
    "id": 51,
    "name": "Tim Carter",
    "email": "tcarter743@aol.com",
    "phone": "",
    "location": "4125 San Ysidro Way, Rockledge, Florida, 32955, United States, 32955",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 22.49,
    "totalAmount": 52.48,
    "instagram": "https://www.instagram.com/kerlamarie/"
  },
  {
    "id": 52,
    "name": "Veronica Moeller",
    "email": "veronicamoeller@icloud.com",
    "phone": "",
    "location": "238 W broad street, Souderton, Pennsylvania, 18969, United States, 18969",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://www.instagram.com/Youngartistinthemist/"
  },
  {
    "id": 53,
    "name": "Marcia Jacqueline Myrie",
    "email": "marciajacquelinem@gmail.com",
    "phone": "",
    "location": "Viale dell'Appennino, 390, Forl\u00ec, 45, 47121, Italy, 47121",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "https://www.instagram.com/Phil_knight_photography/"
  },
  {
    "id": 54,
    "name": "Makenna Heard",
    "email": "makennath3@gmail.com",
    "phone": "",
    "location": "1013 N 12th St, Augusta, Arkansas, 72006, United States, 72006",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 50.0,
    "totalAmount": 50.0,
    "instagram": "https://www.instagram.com/Phil_knight_photography/"
  },
  {
    "id": 55,
    "name": "Leiana Webb",
    "email": "leianalwebb@gmail.com",
    "phone": "",
    "location": "2270 Synergy, Irvine, California, 92614, United States, 92614",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 34.0,
    "totalAmount": 34.0,
    "instagram": "https://www.instagram.com/Phil_knight_photography/"
  },
  {
    "id": 56,
    "name": "Erik Rosa",
    "email": "info@erikrosaphotography.com",
    "phone": "",
    "location": "4761 Broadway #5j, New York, New York, 10034, United States, 10034",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 34.0,
    "totalAmount": 34.0,
    "instagram": "https://www.instagram.com/model_jeannie/"
  },
  {
    "id": 57,
    "name": "Jennifer Conley",
    "email": "jenniferconley980@gmail.com",
    "phone": "",
    "location": "4730 Katherine Lane, Memphis, Tennessee, 38141, United States, 38141",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 50.0,
    "totalAmount": 50.0,
    "instagram": "https://www.instagram.com/Nia_aaliyah/"
  },
  {
    "id": 58,
    "name": "Olivia Quantz",
    "email": "oquantz@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 23.99,
    "totalAmount": 23.99,
    "instagram": "https://instagram.com/model_michellea1?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 59,
    "name": "Logan Kline",
    "email": "kline_logan@hotmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": "https://instagram.com/model_michellea1?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 60,
    "name": "JaShanna Graves",
    "email": "gjash1918@gmail.com",
    "phone": "",
    "location": "5505 Perching Place, Lithonia, Georgia, 30058, United States, 30058",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://Instagram.com/s.tmarie"
  },
  {
    "id": 61,
    "name": "Yuvelky Diaz",
    "email": "yuvelkyd@gmail.com",
    "phone": "",
    "location": "1323 Clinton Ave, Bronx, New York, 10456-2773, United States, 10456-2773",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 50.0,
    "totalAmount": 50.0,
    "instagram": "https://www.instagram.com/desiree.a.brown/"
  },
  {
    "id": 62,
    "name": "Svanah Chinnis",
    "email": "piecesyne@gmail.com",
    "phone": "",
    "location": "654 Biltmore Dr, Virginia Beach, Virginia, 23454-3454, United States, 23454-3454",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 70.0,
    "totalAmount": 70.0,
    "instagram": "https://www.instagram.com/desiree.a.brown/"
  },
  {
    "id": 63,
    "name": "Dee Smikle",
    "email": "modeldeethang@outlook.com",
    "phone": "",
    "location": "4103 Brentwood Lane, Waukegan, Illinois, 60087, United States, 60087",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://www.instagram.com/shotsbyjewan/"
  },
  {
    "id": 64,
    "name": "Savanna Stevens",
    "email": "savannastevens1211@gmail.com",
    "phone": "",
    "location": "4333 Glen Este-Withamsville Rd apt 106, Cincinnati, Ohio, 45245-1526, United States, 45245-1526",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://www.instagram.com/isabelllagabriellle/?hl=en"
  },
  {
    "id": 65,
    "name": "Joseph Diaz",
    "email": "josephjanlee@gmail.com",
    "phone": "",
    "location": "2541 Academy Ave, Deltona, Florida, 32738-2563, United States, 32738-2563",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://www.instagram.com/a.diorr_//"
  },
  {
    "id": 66,
    "name": "Peter Torres",
    "email": "pe_torres91@yahoo.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 23.99,
    "totalAmount": 23.99,
    "instagram": "https://www.instagram.com/model_tae/"
  },
  {
    "id": 67,
    "name": "Kathleen Nashira Camejo",
    "email": "ladykat1424@yahoo.com",
    "phone": "",
    "location": "3207 Abercorn Ave, Atlanta, Georgia, 30346, United States, 30346",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 98.0,
    "totalAmount": 98.0,
    "instagram": "https://www.instagram.com/mscupcakexo"
  },
  {
    "id": 68,
    "name": "tabitha Shockley",
    "email": "enlighten2heal@gmail.com",
    "phone": "",
    "location": "6109 Old Shawnee Rd, Milford, Delaware, 19963-3366, United States, 19963-3366",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "https://www.instagram.com/astroonaii/"
  },
  {
    "id": 69,
    "name": "Ezra Murry",
    "email": "jokervisuals@gmail.com",
    "phone": "",
    "location": "3925 W Virden Ct, Peoria, Illinois, 61615-2976, United States, 61615-2976",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "https://www.instagram.com/astroonaii/"
  },
  {
    "id": 70,
    "name": "Daevwana Holden",
    "email": "daevwana@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": "https://www.instagram.com/Bakinmycake420/"
  },
  {
    "id": 71,
    "name": "Brittany Shenault",
    "email": "brittanyshenault@gmail.com",
    "phone": "",
    "location": "2777 S Arizona Ave, Chandler, Arizona, 85286-1801, United States, 85286-1801",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 71.99,
    "instagram": "www.instagram.com/Misshighsadity"
  },
  {
    "id": 72,
    "name": "salmata kamara",
    "email": "missmatak17@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 14.99,
    "totalAmount": 14.99,
    "instagram": "https://instagram.com/xiagemshow?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 73,
    "name": "Delbert Fisher",
    "email": "dlfishe2@comcast.net",
    "phone": "",
    "location": "234 Oak St, Battle Creek, Michigan, 49037-1272, United States, 49037-1272",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 50.0,
    "totalAmount": 50.0,
    "instagram": "https://instagram.com/xiagemshow?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 74,
    "name": "Marcos Green",
    "email": "ronmarcos900@gmail.com",
    "phone": "",
    "location": "127 Greyrock Pl Apt. 1603, Stamford, Connecticut, 06901, United States, 6901",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 96.8,
    "instagram": "https://instagram.com/xiagemshow?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 75,
    "name": "Isabella Covington",
    "email": "icovington32203@gmail.com",
    "phone": "",
    "location": "320 Freedom Trail, West Union, South Carolina, 29696-3709, United States, 29696-3709",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://www.instagram.com/aprilameliaphoto/"
  },
  {
    "id": 76,
    "name": "Adriana Santiago",
    "email": "asantiago2034@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 17.99,
    "totalAmount": 17.99,
    "instagram": "https://www.instagram.com/melaninmaven329/"
  },
  {
    "id": 77,
    "name": "Kevin Biggens",
    "email": "frostylenss@gmail.com",
    "phone": "",
    "location": "3509 Elgin St apt 506, Houston, Texas, 77004-3624, United States, 77004-3624",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "Http://www.instagram.com/makeupbykerla"
  },
  {
    "id": 78,
    "name": "Yaril Rivera",
    "email": "yaril.riveraperez@gmail.com",
    "phone": "",
    "location": "2820 Compass Ct, Fort Bragg, North Carolina, 28307, United States, 28307",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 43.6,
    "totalAmount": 43.6,
    "instagram": "https://instagram.com/queen_laurwis?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 79,
    "name": "Devon Johnson",
    "email": "devondjohnson@gmail.com",
    "phone": "",
    "location": "22755 Nottingham Ln unit 1525, Southfield, Michigan, 48033-3365, United States, 48033-3365",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 50.0,
    "totalAmount": 50.0,
    "instagram": "https://www.instagram.com/paige.seale/"
  },
  {
    "id": 80,
    "name": "Terrell Jordan",
    "email": "thjvisuals@gmail.com",
    "phone": "",
    "location": "1265 Paddock Hills Ave, Cincinnati, Ohio, 45229-1219, United States, 45229-1219",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": ""
  },
  {
    "id": 81,
    "name": "Sherria Chase",
    "email": "moecuts2572@gmail.com",
    "phone": "",
    "location": "99 Wabash Ave N, Battle Creek, Michigan, 49017-4700, United States, 49017-4700",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 50.0,
    "totalAmount": 50.0,
    "instagram": "https://instagram.com/stewartlaytonphoto?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 82,
    "name": "Darrylynn Gates",
    "email": "tiffany.funke92@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 23.99,
    "totalAmount": 23.99,
    "instagram": "https://instagram.com/kittyjewlz?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 83,
    "name": "Allegra Ruhl",
    "email": "allegra.ruhl18@gmail.com",
    "phone": "",
    "location": "569 Arlington Ave, Mansfield, Ohio, 44903-1801, United States, 44903-1801",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 70.0,
    "totalAmount": 70.0,
    "instagram": "https://www.instagram.com/iamsamholly/"
  },
  {
    "id": 84,
    "name": "Mikel Thomas",
    "email": "mikelthomas64@yahoo.com",
    "phone": "",
    "location": "5616 Angora Terrace, Philadelphia, Pennsylvania, 19143-3112, United States, 19143-3112",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://www.instagram.com/thompayson_model_photography/"
  },
  {
    "id": 85,
    "name": "Katherine Chandler",
    "email": "chandlerk57@gmail.com",
    "phone": "",
    "location": "16307 STATE STREET, SOUTH HOLLAND, Illinois, 60473, United States, 60473",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 49.99,
    "totalAmount": 49.99,
    "instagram": "https://www.instagram.com/leonreidphotography/"
  },
  {
    "id": 86,
    "name": "Esteban Vera",
    "email": "lordyoung215@gmail.com",
    "phone": "",
    "location": "5 Cameron Rd., Willow Grove, Pennsylvania, 19090, United States, 19090",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 100.0,
    "totalAmount": 100.0,
    "instagram": "https://www.instagram.com/saint.aubyn/"
  },
  {
    "id": 87,
    "name": "Shiyana Hoyt",
    "email": "akiasphotocreationdesign@gmail.com",
    "phone": "",
    "location": "234 Oak St, Battle Creek, Michigan, 49037-1272, United States, 49037-1272",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "https://www.instagram.com/kpmediaworks/"
  },
  {
    "id": 88,
    "name": "Angel Powell",
    "email": "anightingale02@aol.com",
    "phone": "",
    "location": "436 Georgiana Dr, Middletown, Delaware, 19709, United States, 19709",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "https://www.instagram.com/_jenpenpics/"
  },
  {
    "id": 89,
    "name": "Jonathan Luz",
    "email": "jluzphotography@gmail.com",
    "phone": "",
    "location": "100 Patritos Ridge Drive, Deptford, New Jersey, 08096, United States, 8096",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "-"
  },
  {
    "id": 90,
    "name": "Rreon Jones",
    "email": "rjcreations12.s@gmail.com",
    "phone": "",
    "location": "10566 Marne St, Detroit, Michigan, 48224-1150, United States, 48224-1150",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 42.0,
    "totalAmount": 42.0,
    "instagram": "https://www.instagram.com/nalaophoto//"
  },
  {
    "id": 91,
    "name": "Antony Bannick",
    "email": "antonybannick@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 54.18,
    "instagram": "https://www.instagram.com/pierce_michael1/"
  },
  {
    "id": 92,
    "name": "Jennifer Pray",
    "email": "jennifer.pray@me.com",
    "phone": "",
    "location": "61052 Doe Run Dr, Amite, Louisiana, 70422, United States, 70422",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 229.95,
    "instagram": "https://www.instagram.com/charnicenickole/"
  },
  {
    "id": 93,
    "name": "Brandon Newell",
    "email": "3eyedvisuals@gmail.com",
    "phone": "",
    "location": "11 Barbara Fleshman Ct, Newark, Delaware, 19702, United States, 19702",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 66.0,
    "totalAmount": 66.0,
    "instagram": "https://www.instagram.com/zhaialeyahn/"
  },
  {
    "id": 94,
    "name": "Kayla Wiggins",
    "email": "kaylajmcswain92@yahoo.com",
    "phone": "",
    "location": "6425 Weidlake Dr, Los Angeles, California, 90068, United States, 90068",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 49.99,
    "totalAmount": 49.99,
    "instagram": "https://www.instagram.com/Tomardesde/"
  },
  {
    "id": 95,
    "name": "Jamaal Shepard",
    "email": "barber2373@gmail.com",
    "phone": "",
    "location": "508 Green Oak Dr, North Little Rock, Arkansas, 72118-3127, United States, 72118-3127",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 54.8,
    "totalAmount": 54.8,
    "instagram": "https://www.instagram.com/vabarbie757/"
  },
  {
    "id": 96,
    "name": "Enrique Javier Ma\u00f1\u00f3n",
    "email": "enriquej_manon@icloud.com",
    "phone": "",
    "location": "7033 N 14th Ave, Phoenix, Arizona, 85021, United States, 85021",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 99.98,
    "totalAmount": 99.98,
    "instagram": "https://www.instagram.com/2ndlook_photography/"
  },
  {
    "id": 97,
    "name": "Lyndon Johnson",
    "email": "hwarangwarrior@msn.com",
    "phone": "",
    "location": "106 Red Oak Dr., Goldsboro, North Carolina, 27530, United States, 27530",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 33.99,
    "totalAmount": 33.99,
    "instagram": "https://www.instagram.com/capturedby.malc/"
  },
  {
    "id": 98,
    "name": "Helen Smith",
    "email": "geminimodel23@yahoo.com",
    "phone": "",
    "location": "4700 Sagebrush Trail Apt B, Austin, Texas, 78745-1538, United States, 78745-1538",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 101.98,
    "totalAmount": 101.98,
    "instagram": "https://www.instagram.com/imagesbymrmike/"
  },
  {
    "id": 99,
    "name": "Jesse Tshiyoyi",
    "email": "jesterphoton@gmail.com",
    "phone": "",
    "location": "4765 AVENUE SAINT-KEVIN,, Montreal, Pennsylvania, H3W 1N8, United States, H3W 1N8",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://www.instagram.com/shotsbyjay2020/"
  },
  {
    "id": 100,
    "name": "Branden Ervin",
    "email": "erv483@yahoo.com",
    "phone": "",
    "location": "36002 Hunter Ave Apt 11216, westland, Michigan, 48185-6650, United States, 48185-6650",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://instagram.com/Aperturestudio_"
  },
  {
    "id": 101,
    "name": "BLUEVISIONBTY Val",
    "email": "bluevisionbty@gmail.com",
    "phone": "",
    "location": "2941 Rue Alphonse-de Lamartine, Laval, Quebec, H7P 6B8, Canada, H7P 6B8",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": "https://instagram.com/kasko.photo?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 102,
    "name": "Olivia Lytle",
    "email": "lytle.olivia@yahoo.com",
    "phone": "",
    "location": "41 Short Street, Brevard, North Carolina, 28712, United States, 28712",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 200.02,
    "totalAmount": 200.02,
    "instagram": "https://www.instagram.com/zelly.yy/"
  },
  {
    "id": 103,
    "name": "Amanda Hinds",
    "email": "amandahbears@gmail.com",
    "phone": "",
    "location": "9085 E Mississippi Ave apt a101, Denver, Colorado, 80247-2068, United States, 80247-2068",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": "https://www.instagram.com/adabednarzphoto/?igshid=YmMyMTA2M2Y%3D"
  },
  {
    "id": 104,
    "name": "Kelsey Burrows",
    "email": "ballroomdancer88@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 22.5,
    "totalAmount": 22.5,
    "instagram": "https://www.instagram.com/rprioleauphotography/"
  },
  {
    "id": 105,
    "name": "Olivia Lytle",
    "email": "lytle.ob@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 49.99,
    "totalAmount": 49.99,
    "instagram": "http://www.instagram.com/capitalPhil"
  },
  {
    "id": 106,
    "name": "Terayah Overton",
    "email": "toverton2018@gmail.com",
    "phone": "",
    "location": "1 Yorktown Ct, Newark, Delaware, 19702-5213, United States, 19702-5213",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": "https://instagram.com/ghost_town_photography?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 107,
    "name": "Fara Francis",
    "email": "ffrancis420@gmail.com",
    "phone": "",
    "location": "8865 W Teton Cir, Littleton, Colorado, 80128-7115, United States, 80128-7115",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 79.98,
    "totalAmount": 119.98,
    "instagram": "https://www.instagram.com/sunandpomstudio/"
  },
  {
    "id": 108,
    "name": "Kynan Chambers",
    "email": "kynanphotography@gmail.com",
    "phone": "",
    "location": "1363 N 31st St apt 220, Philadelphia, Pennsylvania, 19121, United States, 19121",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 99.98,
    "totalAmount": 99.98,
    "instagram": "Https://www.instagram.com/scotthallfotos"
  },
  {
    "id": 109,
    "name": "John Hall",
    "email": "barberjcllc@outlook.com",
    "phone": "",
    "location": "5447 Maryland St, Merrillville, Indiana, 46410-1636, United States, 46410-1636",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": "www.instagram.com/deadstockprouctions"
  },
  {
    "id": 110,
    "name": "Loliedia Reynolds",
    "email": "beanie1pie@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 22.49,
    "totalAmount": 22.49,
    "instagram": "https://www.instagram.com/tonynothollywood/?igshid=YmMyMTA2M2Y%3D"
  },
  {
    "id": 111,
    "name": "Valery Foote",
    "email": "valeryjeanette@gmail.com",
    "phone": "",
    "location": "5741 Grant St Apt. 204, Merrillville, Indiana, 46410, United States, 46410",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 79.98,
    "totalAmount": 79.98,
    "instagram": "https://www.instagram.com/yoobeckyy/?igshid=YmMyMTA2M2Y%3D"
  },
  {
    "id": 112,
    "name": "Brittney Booze",
    "email": "luxeriousbodytreatz@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 24.99,
    "totalAmount": 47.48,
    "instagram": "https://www.instagram.com/becksrock/"
  },
  {
    "id": 113,
    "name": "Kaniya Lawrence",
    "email": "kaniyalawrence0@gmail.com",
    "phone": "",
    "location": "Ottawa House East, Toledo, Ohio, 43606, United States, 43606",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://www.instagram.com/marlena.elise/?igshid=YmMyMTA2M2Y%3DD"
  },
  {
    "id": 114,
    "name": "Chellese Grove",
    "email": "chellesegrove@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": "https://www.instagram.com/b.ooonnng/"
  },
  {
    "id": 115,
    "name": "Jason Nuttle",
    "email": "jason@jasonnuttle.com",
    "phone": "",
    "location": "1016 Clare Avenue, Suite 5, West Palm Beach, Florida, 33401, United States, 33401",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 149.97,
    "totalAmount": 149.97,
    "instagram": "https://www.instagram.com/smoothshutter.photo/"
  },
  {
    "id": 116,
    "name": "Justin Gaspaire",
    "email": "courtland61079@gmail.com",
    "phone": "",
    "location": "5601 N 37th St #NN3, Tacoma, Washington, 98407, United States, 98407",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": "HTTPS://www.instagram.com/@_.honeybear._x"
  },
  {
    "id": 117,
    "name": "Amaya Smith",
    "email": "amayaiam1@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 22.49,
    "totalAmount": 22.49,
    "instagram": "https://www.instagram.com/noma.iya/"
  },
  {
    "id": 118,
    "name": "Madison Smith",
    "email": "maddybug.smith@gmail.com",
    "phone": "",
    "location": "1444 S 50 W, Payson, Utah, 84651, United States, 84651",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 66.0,
    "totalAmount": 166.01,
    "instagram": "https://www.instagram.com/stellarviewboudoir/"
  },
  {
    "id": 119,
    "name": "Brian Jones",
    "email": "colbidennettclothing@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 24.99,
    "totalAmount": 24.99,
    "instagram": "https://www.instagram.com/Phil_knight_photography/"
  },
  {
    "id": 120,
    "name": "Tauheedah Abraham",
    "email": "abrahtee@yahoo.com",
    "phone": "",
    "location": "221 Mill Branch Way, North Augusta, South Carolina, 29860-8622, United States, 29860-8622",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 49.99,
    "totalAmount": 49.99,
    "instagram": "https://www.instagram.com/innervolve_/"
  },
  {
    "id": 121,
    "name": "David Young",
    "email": "bradyoungmedia@gmail.com",
    "phone": "",
    "location": "1224 Harrison Rd, Colorado Springs, Colorado, 80905-3519, United States, 80905-3519",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": "https://www.instagram.com/Melaninmaven329/"
  },
  {
    "id": 122,
    "name": "Dyvine Wallace",
    "email": "dyvinwallace@yahoo.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 14.99,
    "totalAmount": 14.99,
    "instagram": "https://www.instagram.com/luccirashaed//"
  },
  {
    "id": 123,
    "name": "Rashad Satterfield",
    "email": "r.satterfield92@gmail.com",
    "phone": "",
    "location": "2 Meteor Ct, Parkville, Maryland, 21234-6027, United States, 21234-6027",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 66.0,
    "totalAmount": 66.0,
    "instagram": "https://instagram.com/rociodeleonpr?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 124,
    "name": "Khalila Mix",
    "email": "mixkhalila@gmail.com",
    "phone": "",
    "location": "5248 Harvard Rd, Detroit, Michigan, 48224-2166, United States, 48224-2166",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 49.99,
    "totalAmount": 49.99,
    "instagram": "https://www.instagram.com/leilani.arj/"
  },
  {
    "id": 125,
    "name": "James Dinkins",
    "email": "jimmydinkins04@gmail.com",
    "phone": "",
    "location": "PO Bx 472, Saratoga, Wyoming, 82331, United States, 82331",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": "https://www.instagram.com/satinestudios//"
  },
  {
    "id": 126,
    "name": "Brandon Chase",
    "email": "bchase1080@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 22.49,
    "totalAmount": 22.49,
    "instagram": "https://www.instagram.com/its_didine/"
  },
  {
    "id": 127,
    "name": "rileigh hobgood",
    "email": "rileighhobgood@gmail.com",
    "phone": "",
    "location": "3431 Covenant Rd Apt B2, Columbia, South Carolina, 29204-4279, United States, 29204-4279",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "http://instagram.com/marlalou_/"
  },
  {
    "id": 128,
    "name": "Shaun Baker",
    "email": "shaunbphotography20@gmail.com",
    "phone": "",
    "location": "3713 Suri Rise Ln, Herriman, Utah, 84096, United States, 84096",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 104.0,
    "totalAmount": 104.0,
    "instagram": "https://www.instagram.com/4everTanisha_/"
  },
  {
    "id": 129,
    "name": "Stephen Sieverin",
    "email": "sev690@yahoo.com",
    "phone": "",
    "location": "5550 natalie Drive, Oak Forest, Illinois, 60452, United States, 60452",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 99.98,
    "totalAmount": 99.98,
    "instagram": "https://www.instagram.com/princessadanne/"
  },
  {
    "id": 130,
    "name": "Candace DeStefano",
    "email": "candace.destefano@hotmail.com",
    "phone": "",
    "location": "130 Summer Ave, Newark, New Jersey, 07104-1903, United States, 07104-1903",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://www.instagram.com/naythedivine/"
  },
  {
    "id": 131,
    "name": "Yvona gonzalez",
    "email": "yvonaygonzalez12@yahoo.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 29.99,
    "totalAmount": 29.99,
    "instagram": "https://www.posebypxphotography.com/"
  },
  {
    "id": 132,
    "name": "Carlos Alexander",
    "email": "alexander0124@yahoo.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 22.49,
    "totalAmount": 22.49,
    "instagram": "https://instagram.com/charleslongphotography2.0?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 133,
    "name": "Christopher Rayburn",
    "email": "cray1476@gmail.com",
    "phone": "",
    "location": "1912 W Henderson St, Chicago, Illinois, 60657-2017, United States, 60657-2017",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 22.49,
    "totalAmount": 72.48,
    "instagram": "https://instagram.com/saniyyarenee?igshid=YmMyMTA2M2Y="
  },
  {
    "id": 134,
    "name": "Britney Ferguson",
    "email": "ferguson.britneya@gmail.com",
    "phone": "",
    "location": "5700 Sepulveda Blvd, Los Angeles, California, 91411-2901, United States, 91411-2901",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://www.instagram.com/Taylornlang/"
  },
  {
    "id": 135,
    "name": "Brittney Patterson",
    "email": "bcollins7112@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 22.49,
    "totalAmount": 22.49,
    "instagram": "www.instagram.com/queensoleil22"
  },
  {
    "id": 136,
    "name": "Victoria Davis",
    "email": "mamaduke91@gmail.com",
    "phone": "",
    "location": "3405 N Shepherd Dr Apt. 1104, Houston, Texas, 77018, United States, 77018",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://www.instagram.com/posebypxphotography/"
  },
  {
    "id": 137,
    "name": "Jeff LaPread",
    "email": "fl4shphotography@gmail.com",
    "phone": "",
    "location": "3350 Tarian Way, Decatur, Georgia, 30034-5517, United States, 30034-5517",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 52.0,
    "totalAmount": 52.0,
    "instagram": "https://www.instagram.com/posebypxphotography/"
  },
  {
    "id": 138,
    "name": "Dana Uscanga",
    "email": "uscanga.dana12@gmail.com",
    "phone": "",
    "location": "3380 Lincoln Ave, Ogden, Utah, 84401-4023, United States, 84401-4023",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://www.instagram.com/posebypxphotography/"
  },
  {
    "id": 139,
    "name": "Guile Angel",
    "email": "angelica.guile@yahoo.com",
    "phone": "",
    "location": "7808 Diamond Trail, Lago Vista, Texas, 78645-4443, United States, 78645-4443",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://www.instagram.com/posebypxphotography/"
  },
  {
    "id": 140,
    "name": "Nyaweka Bidiit",
    "email": "Nyawekabidiit@gmail.com",
    "phone": "",
    "location": "1248 Brister Dr, Salt Lake City, Utah, 84123, United States, 84123",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://www.instagram.com/posebypxphotography/"
  },
  {
    "id": 141,
    "name": "Vince Blackham",
    "email": "vinblackham@gmail.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 22.49,
    "totalAmount": 22.49,
    "instagram": "https://www.instagram.com/posebypxphotography/"
  },
  {
    "id": 142,
    "name": "Sidney Jackson",
    "email": "jacksonsidney1@gmail.com",
    "phone": "",
    "location": "462 Walker Ranch Drive, Fuquay Varina, North Carolina, 27526-4488, United States, 27526-4488",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 49.99,
    "totalAmount": 99.98,
    "instagram": "https://www.instagram.com/jenae.cherie/"
  },
  {
    "id": 143,
    "name": "Sophie Caen",
    "email": "sophiedecaen@yahoo.com",
    "phone": "",
    "location": "65-61 Saunders St #2g, Rego Park, New York, 11374, United States, 11374",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "HTTPS://www.Instagram.com/@lacquanscott.photos"
  },
  {
    "id": 144,
    "name": "Olivia Bell",
    "email": "oliviabell321@gmail.com",
    "phone": "",
    "location": "421 E Mcintosh S APT 2G, Milledgeville, Georgia, 31061, United States, 31061",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": ""
  },
  {
    "id": 145,
    "name": "Alexis Sylvester",
    "email": "alexis.sylvester@fox.com",
    "phone": "",
    "location": "92 Wood Lake Dr, Middletown, New York, 10940-4274, United States, 10940-4274",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 66.0,
    "totalAmount": 66.0,
    "instagram": "instagram.com/dubzz_photography"
  },
  {
    "id": 146,
    "name": "Camille Nakashima",
    "email": "camilledecaen@yahoo.com",
    "phone": "",
    "location": "65-61 Saunders Street, Apt 2G, Rego Park, New York, 11374, United States, 11374",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://www.instagram.com/lipstickandsneakerz/"
  },
  {
    "id": 147,
    "name": "Michael Irvin",
    "email": "mcirvin24@gmail.com",
    "phone": "",
    "location": "462 Walker Ranch Dr, Fuquay-Varina, North Carolina, 27526-4488, United States, 27526-4488",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 49.99,
    "totalAmount": 49.99,
    "instagram": "https://www.instagram.com/Tomardesde/"
  },
  {
    "id": 148,
    "name": "Mark Murphy III",
    "email": "smurfmark.geo@yahoo.com",
    "phone": "",
    "location": "",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 22.49,
    "totalAmount": 22.49,
    "instagram": "https://www.instagram.com/thorfanthoeun12/"
  },
  {
    "id": 149,
    "name": "Tiffany Wilson",
    "email": "Tiffinfo87@gmail.com",
    "phone": "",
    "location": "433 John F. Kennedy Blvd, Bayonne, New Jersey, 07002, United States, 7002",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 39.99,
    "totalAmount": 39.99,
    "instagram": "https://www.instagram.com/lefteyephotographer/"
  },
  {
    "id": 150,
    "name": "Carlos Velazquez",
    "email": "carlos.antoniovelazquez@hotmail.com",
    "phone": "",
    "location": "979 Arbor crowne, Lawrenceville, Georgia, 30045, United States, 30045",
    "magazine": "BLACKCRUZE",
    "status": "Buyer",
    "amount": 49.99,
    "totalAmount": 49.99,
    "instagram": "https://www.instagram.com/smoothshutter.photo/"
  }
];