export const CUSTOMERS = [
  {
    "id": 10034,
    "name": "Kelsie Roy",
    "email": "roykelsie@gmail.com",
    "magazine": "Elfero",
    "amount": 60,
    "currency": "USD",
    "status": "Buyer",
    "address": "123 Maple St, Paris",
    "zip": "75001",
    "model": "Portrait",
    "stage": "Pro",
    "insta": "@kelsieroy"
  },
  {
    "id": 10033,
    "name": "Robyn Fitzgerald",
    "email": "robynfitzgerald34@gmail.com",
    "magazine": "Elfero",
    "amount": 54.8,
    "currency": "USD",
    "status": "Buyer",
    "address": "22 King St, London",
    "zip": "WC2N",
    "model": "Fashion",
    "stage": "Pro",
    "insta": "@robynfitz"
  },
  {
    "id": 10032,
    "name": "Sharon Brough",
    "email": "shrn1972@gmail.com",
    "magazine": "Elfero",
    "amount": 29.99,
    "currency": "USD",
    "status": "Viewer",
    "address": "8 York Rd, Sydney",
    "zip": "2000",
    "model": "",
    "stage": "",
    "insta": ""
  },
  {
    "id": 10031,
    "name": "Maxwell Dacosta",
    "email": "maxwelldondacosta@gmail.com",
    "magazine": "Elfero",
    "amount": 66,
    "currency": "USD",
    "status": "Buyer",
    "address": "45 Bay St, Mumbai",
    "zip": "400001",
    "model": "Editorial",
    "stage": "Pro",
    "insta": "@maxdacosta"
  },
  {
    "id": 10030,
    "name": "Kelly Jean",
    "email": "kj.model.mt@gmail.com",
    "magazine": "Elfero",
    "amount": 0,
    "currency": "USD",
    "status": "Viewer",
    "address": "55 Rue Oberkampf, Paris",
    "zip": "75011",
    "model": "",
    "stage": "",
    "insta": ""
  },
  {
    "id": 10456,
    "name": "Lorenzo Torres",
    "email": "dappershoots@gmail.com",
    "magazine": "BlackCruze",
    "amount": 23.99,
    "currency": "USD",
    "status": "Buyer",
    "address": "99 High St, NY",
    "zip": "10001",
    "model": "Street",
    "stage": "Pro",
    "insta": "@lorenzot"
  },
  {
    "id": 10455,
    "name": "DuBose",
    "email": "demarcus.dubose@gmail.com",
    "magazine": "BlackCruze",
    "amount": 0,
    "currency": "USD",
    "status": "Viewer",
    "address": "21 Elm St, LA",
    "zip": "90001",
    "model": "",
    "stage": "",
    "insta": ""
  },
  {
    "id": 10454,
    "name": "Remi Morgan",
    "email": "remorgangra@gmail.com",
    "magazine": "BlackCruze",
    "amount": 54.8,
    "currency": "USD",
    "status": "Buyer",
    "address": "77 Queen St, Toronto",
    "zip": "M5H",
    "model": "Lifestyle",
    "stage": "Pro",
    "insta": "@remimorgan"
  },
  {
    "id": 10453,
    "name": "Joi Crawford",
    "email": "joic17@gmail.com",
    "magazine": "BlackCruze",
    "amount": 70,
    "currency": "USD",
    "status": "Buyer",
    "address": "12 Pine St, Chicago",
    "zip": "60601",
    "model": "Runway",
    "stage": "Rising",
    "insta": "@joicrawford"
  },
  {
    "id": 10394,
    "name": "Anisa Henderson",
    "email": "anisagenesis@gmail.com",
    "magazine": "BlackCruze",
    "amount": 0,
    "currency": "USD",
    "status": "Viewer",
    "address": "33 Cedar Rd, Austin",
    "zip": "73301",
    "model": "",
    "stage": "",
    "insta": ""
  }
];